CREATE TABLE IF NOT EXISTS usuarios (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	email text NOT NULL,
	senha text NOT NULL,
	nome text NULL,
	CONSTRAINT clientes_pk PRIMARY KEY (id)
);